name: api-core
services:
  node:
    env_file:
      - .env.test
    profiles: ["E2E"]
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'

  redis:
    profiles: ["integration", "cacheDB"]
    image: redis:alpine
    ports:
      - '6379:6379'

  memcached:
    profiles: ["integration", "cacheDB"]
    image: memcached:alpine
    ports:
      - '11211:11211'
  
  mysql:
    profiles: ["integration", "DB"]
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'
      - '33060:33060'
    healthcheck:
      test: mysqladmin ping -h localhost -u test --password=password
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s