name: api-core
services:
  node:
    env_file:
      - .env.test
    profiles: ["E2E"]
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'

  redis:
    profiles: ["integration", "cacheDB"]
    image: redis:alpine
    ports:
      - '6379:6379'

  memcached:
    profiles: ["integration", "cacheDB"]
    image: memcached:alpine
    ports:
      - '11211:11211'