version: '3.32'
services:
  node:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:${PORT_HTTPS}/health"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s