# https://github.com/babel/babel/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
# https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
name: "Bug Report"
description: We broke something, again
title: "[Bug]: "
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!** Please make sure you read our [issue guidelines](../blob/main/CONTRIBUTING.md) first, then fill out the fields below.

        If you're unsure whether the issue you're having is a bug, you can post in [Discussions](../discussions) instead.

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Make new project
        2. Run `make package`
        3. …
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: input
    id: host-os-version
    attributes:
      label: Which runtime version did you install?
      placeholder: "e.g. Nodejs 12.x"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----
        
        # Details of your host machine (the device you are running on)

  - type: textarea
    id: bug-logs
    attributes:
      label: Paste any relevant logs, error output, etc.
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (If it's long, please paste to https://gist.github.com/ and insert the link here.)
      render: Shell

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context you can provide about the problem here.