name: ESLint

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: latest

      - run: npm install
      - run: npm run lint